#---------------------------------------
#-------------- Exec-once --------------
#---------------------------------------

exec-once = hyprpaper
exec-once = hypridle
exec-once = hyprsunset
exec-once = waybar
exec-once = swaync
exec-once = sleep 2 && hyprctl dispatch dpms off && sleep 0.5 && hyprctl dispatch dpms on
