#---------------------------------------
#-------------- Exec-once --------------
#---------------------------------------

exec-once = hyprpaper 
exec-once = waybar & swaync
exec-once = hyprsunset
exec-once = sleep 2 && hyprctl dispatch dpms off && sleep 0.5 && hyprctl dispatch dpms on