# -- Exec Once --
exec-once = hyprpaper 
exec-once = waybar & swaync
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-2
exec-once = hyprsunset
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = keyd-application-mapper -d