#------------------------------------------------------------------------------
# ---- Triggers & Window Management --------
#------------------------------------------------------------------------------
bind = SUPER, RETURN, exec, kitty
bind = SUPER, W, killactive,
bind = SUPER, M, exec, wlogout
bind = SUPER, E, exec, nautilus
bind = SUPER, SPACE, exec, $menu
bind = SUPER_SHIFT, Q, exec, hyprlock

# --- Window State Controls ---
bind = SUPER, F, fullscreen, 0       # Toggle Fullscreen (In / Out)
bind = SUPER, P, layoutmsg, togglesplit        # Toggle Split Direction (Vertical / Horizontal)
bind = SUPER, V, togglefloating

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

#------------------------------------------------------------------------------
# -- Basic Navigation --
#------------------------------------------------------------------------------

# --- Workspace Navigation ---

# Move focus to a workspace with SUPER + [0-9]
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5

# Move active window to a workspace
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5

# Special workspace
bind = SUPER, 0, togglespecialworkspace, magic
bind = SUPER SHIFT, 0, movetoworkspace, special:magic

# Scroll through workspaces
bind = SUPER, mouse_down, workspace, e+1
bind = SUPER, mouse_up, workspace, e-1

# --- VIM NAVIGATION ---

# Move focus with SUPER + HJKL
bind = SUPER, H, movefocus, l
bind = SUPER, L, movefocus, r
bind = SUPER, K, movefocus, u
bind = SUPER, J, movefocus, d

# --- ARROW KEY NAVIGATION ---

# Move focus with SUPER + Arrow Keys
bind = SUPER, left,  movefocus, l
bind = SUPER, right, movefocus, r
bind = SUPER, up,    movefocus, u
bind = SUPER, down,  movefocus, d

# Swap windows with SUPER + SHIFT + HJKL
bind = SUPER SHIFT, H, movewindow, l
bind = SUPER SHIFT, L, movewindow, r
bind = SUPER SHIFT, K, movewindow, u
bind = SUPER SHIFT, J, movewindow, d

# Swap windows with SUPER + SHIFT + Arrow Keys
bind = SUPER SHIFT, left,  movewindow, l
bind = SUPER SHIFT, right, movewindow, r
bind = SUPER SHIFT, up,    movewindow, u
bind = SUPER SHIFT, down,  movewindow, d

# -- Screenshot --
bind = SUPER SHIFT, S, exec, hyprshot -m region
bind = SUPER, S, exec, hyprshot -m window
bind = SUPER ALT, W, exec, ~/.config/hypr/scripts/wall_switcher.sh
