#------------------------------------------------------------------------------
# --- Inputs ---
#------------------------------------------------------------------------------
cursor {
    # Force a software cursor fallback layer
    no_hardware_cursors = true

    # Keep the pointer awake and drawn on screen infinitely when static
    inactive_timeout = 0
}